"""
scripts/label_frames.py
───────────────────────
Auto-label all frames in training_manifest.csv using IBTrACS best-track
wind intensity data.

Labeling rules (derived from Dvorak technique intensity thresholds and
standard cyclone structural descriptions):

    eye           : wind >= 120 kts  OR  pressure <= 960 hPa
                    (well-defined eye, tight spiral banding)
    banding       : wind 64–119 kts
                    (organised deep convection, spiral bands visible)
    curved_band   : wind 34–63 kts
                    (developing / weakening, single curved band)
    shear_affected: wind >= 34 kts AND rapid weakening
                    (intensity drop >= 15 kts vs 6h-prior)
    disorganized  : wind < 34 kts
                    (depression / well-marked low, no organised structure)

These are rule-based labels derived from best-track data — they are
consistent with standard WMO/IMD structural descriptions at each
intensity level. Not manually verified against actual satellite imagery.
Label source = 'ibtracs_intensity_rules' must be recorded in docs.

Usage:
    python -m scripts.label_frames
    # Writes: data/ground_truth/ground_truth_labels.csv
"""
from __future__ import annotations

import csv
import os
import sys
from datetime import datetime, timezone, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

MANIFEST_CSV = os.path.join("data", "training_manifest.csv")
OUTPUT_CSV   = os.path.join("data", "ground_truth", "ground_truth_labels.csv")

# Best-track CSVs generated by split_ibtracs.py
BT_FILES = {
    "biparjoy_2023": os.path.join("data", "ground_truth", "biparjoy_2023_best_track.csv"),
    "amphan_2020":   os.path.join("data", "ground_truth", "amphan_2020_best_track.csv"),
    "fani_2019":     os.path.join("data", "ground_truth", "fani_2019_best_track.csv"),
    "tauktae_2021":  os.path.join("data", "ground_truth", "tauktae_2021_best_track.csv"),
    "phailin_2013":  os.path.join("data", "ground_truth", "phailin_2013_best_track.csv"),
    "hudhud_2014":   os.path.join("data", "ground_truth", "hudhud_2014_best_track.csv"),
    "ockhi_2017":    os.path.join("data", "ground_truth", "ockhi_2017_best_track.csv"),
}


def _parse_utc(ts: str) -> datetime:
    """Parse ISO-8601 UTC timestamp."""
    ts = ts.strip().replace("Z", "+00:00")
    return datetime.fromisoformat(ts)


def _load_best_track(event_id: str) -> list[dict]:
    path = BT_FILES[event_id]
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    # Parse numeric fields
    for r in rows:
        r["_ts"]  = _parse_utc(r["timestamp"])
        r["_lat"] = float(r["lat"]) if r["lat"].strip() else None
        r["_lon"] = float(r["lon"]) if r["lon"].strip() else None
        wkt = r.get("wmo_wind_kts", "").strip()
        r["_wind"] = float(wkt) if wkt and wkt not in ("", " ") else None
    return sorted(rows, key=lambda x: x["_ts"])


def _find_nearest(bt_rows: list[dict], target_ts: datetime, tolerance_min: int = 90) -> dict | None:
    """Return the best-track row closest to target_ts within tolerance."""
    best = None
    best_delta = None
    for row in bt_rows:
        delta = abs((row["_ts"] - target_ts).total_seconds())
        if delta <= tolerance_min * 60:
            if best_delta is None or delta < best_delta:
                best = row
                best_delta = delta
    return best


def _assign_label(
    wind_kts: float | None,
    prior_wind: float | None,
) -> str:
    """
    Assign structural pattern label from wind intensity.

    Parameters
    ----------
    wind_kts   : current best-track wind (knots), None if missing
    prior_wind : wind 6h earlier (knots), None if missing
    """
    if wind_kts is None:
        return "disorganized"

    # Rapid weakening: >= 15 kt drop in 6 h while still organised
    if (
        prior_wind is not None
        and wind_kts >= 34
        and (prior_wind - wind_kts) >= 15
    ):
        return "shear_affected"

    if wind_kts >= 120:
        return "eye"
    if wind_kts >= 64:
        return "banding"
    if wind_kts >= 34:
        return "curved_band"
    return "disorganized"


def run() -> None:
    # Load manifest
    with open(MANIFEST_CSV, newline="") as f:
        manifest = list(csv.DictReader(f))

    print(f"Manifest rows: {len(manifest)}")

    # Load best-track tables keyed by event
    bt_tables: dict[str, list[dict]] = {}
    for eid, path in BT_FILES.items():
        if os.path.exists(path):
            bt_tables[eid] = _load_best_track(eid)
            print(f"  {eid}: {len(bt_tables[eid])} best-track rows")
        else:
            print(f"  WARNING: {path} not found — skipping {eid}")

    results: list[dict] = []
    label_counts: dict[str, int] = {}
    skipped = 0

    for row in manifest:
        event_id  = row["event_id"]
        frame_id  = row["file_id"]
        frame_ts  = _parse_utc(row["timestamp"])

        bt = bt_tables.get(event_id)
        if bt is None:
            skipped += 1
            continue

        nearest  = _find_nearest(bt, frame_ts, tolerance_min=90)
        prior_6h = _find_nearest(bt, frame_ts - timedelta(hours=6), tolerance_min=90)

        wind      = nearest["_wind"]  if nearest  else None
        prior_w   = prior_6h["_wind"] if prior_6h else None

        label = _assign_label(wind, prior_w)
        label_counts[label] = label_counts.get(label, 0) + 1

        results.append({
            "event_id":          event_id,
            "frame_id":          frame_id,
            "timestamp":         row["timestamp"],
            "ground_truth_label": label,
            "wind_kts":          wind if wind is not None else "",
            "prior_wind_kts":    prior_w if prior_w is not None else "",
            "label_source":      "ibtracs_intensity_rules",
            "center_lat":        row["center_lat"],
            "center_lon":        row["center_lon"],
        })

    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)
    with open(OUTPUT_CSV, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "event_id", "frame_id", "timestamp",
            "ground_truth_label", "wind_kts", "prior_wind_kts",
            "label_source", "center_lat", "center_lon",
        ])
        writer.writeheader()
        writer.writerows(results)

    print(f"\nWrote {len(results)} labels to {OUTPUT_CSV}")
    print(f"Skipped: {skipped}")
    print("Label distribution:")
    for label, count in sorted(label_counts.items(), key=lambda x: -x[1]):
        pct = count / len(results) * 100
        print(f"  {label:<20} {count:>4}  ({pct:.1f}%)")


if __name__ == "__main__":
    run()
